name: Manual Deploy (Server Only)

on: workflow_dispatch

jobs:
  build:
    name: Manual Deploy (Server Only)

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # os: [macos-latest, ubuntu-latest, windows-latest]
        os: [ubuntu-latest]
        node-version: [15.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm install

    - run: cd server && npm run setup

    - run: cd server && npm run lint

    - run: cd server && npm run build

    - name: Install caprover
      run: npm install -g caprover

    - name: Caprover Deploy
      run: caprover deploy -h 'https://captain.rootrpgapi.magpiegames.com' -p '${{ secrets.CAPROVER_PASSWORD }}' -b 'master' -a 'rootrpgapi'
