name: Manual Deploy Dev (Server Only)

on: workflow_dispatch

jobs:
  build:
    name: Manual Deploy Dev (Server Only)

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # os: [macos-latest, ubuntu-latest, windows-latest]
        os: [ubuntu-latest]
        node-version: [15.x]

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - run: npm install && npm run setup
    
    - run: cd server && npm run lint
      
    - run: cd server && npm run build

    - name: Deploy Server
      uses: AlexxNB/caprover-action@v1
      with:
        server: 'https://captain.rootrpgapi.magpiegames.com'
        password: '${{ secrets.CAPROVER_PASSWORD }}'
        appname: 'rootrpgapi'
