name: Manual Deploy

on: workflow_dispatch

jobs:
  build:
    name: Manual Deploy

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # os: [macos-latest, ubuntu-latest, windows-latest]
        os: [ubuntu-latest]
        node-version: [15.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm install && npm run setup

    - run: npm run lint

    - run: npm run build

    - name: Install caprover
      run: npm install -g caprover

    - name: Caprover Deploy
      run: caprover deploy -h 'https://captain.rootrpgapi.magpiegames.com' -p '${{ secrets.CAPROVER_PASSWORD }}' -b 'master' -a 'rootrpgapi'

    - name: Deploy to Netlify
      uses: nwtgck/actions-netlify@v1.1
      with:
        publish-dir: './client/dist'
        production-branch: master
        github-token: ${{ secrets.GITHUB_TOKEN }}
        deploy-message: "Deploy from GitHub Actions"
        enable-pull-request-comment: false
        enable-commit-comment: true
        overwrites-pull-request-comment: true
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
